name: Read Properties
description: Read property from java properties files.
author: Christian Dräger
branding:
  icon: 'list'
  color: 'yellow'
inputs:
  path:
    description: 'The path to properties file to read'
    required: true
  properties:
    description: 'The properties you want to read. Space separated'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.properties }}
